In [1]:
import numpy as np

In [58]:
arr1 = np.array((1,2,3,4,5,6,7,8,9))
arr2 = np.array((11,12,13,14,15,16,17,18,19))
print(arr1)
print(arr2)
print(np.add(arr1,arr2))
print(type(arr1))
print(type(arr2))
arr3 = np.arange(1,100,1,dtype = np.int32)
print(arr3)
print(type(arr3))
arr4 = np.linspace(1,100,100, dtype = np.float64)
print(arr4)
print(type(arr4)) #return data type of given request
print(arr4.shape) #return shape of the array (row,colume)
print(arr4.ndim) #return number of dimensions
print(arr4.dtype) #return data type of the array
print(arr4.size) #return total number of items
print(arr4.nbytes) #return number of bytes

#indexing and reshape

arr5 = arr4.reshape(4,25) #Returns an array containing the same data with a new shape
#use array.reshape(raw,colume)
print(arr5)
print(arr5.dtype)
print(arr5.size)
print(arr5.shape)
print(arr5.ndim)

#index
#indexing (start(inclusive),stop(exclusive))
print(arr5[1:2, 20:])
print(arr5[:,20:])
print(arr5[:,-5:]) #negetive indexing ends on -1

#copy
#To replace the value of certain data point without changing main array use  array.copy()
arr6 = arr5.copy()
print(arr6)
arr6[:,20:] = 150
print(arr6) 
print(arr5)


[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[12 14 16 18 20 22 24 26 28]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
<class 'numpy.ndarray'>
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
<class 'numpy.ndarray'>
(100,)
1
float