In [1]:
import numpy as np

In [36]:
a = np.array([1,2,3,4], int)
b = np.array([1,2,3,4,5,6], float)

In [37]:
b = b.reshape(3,2)

In [38]:
#print matrix
print(a)
print(b)

[1 2 3 4]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [39]:
#diamensions
print(a.ndim)
print(b.ndim)

1
2


In [40]:
print(a.dtype)

int32


In [41]:
print(b.dtype)

float64


In [42]:
b.dtype

dtype('float64')

In [43]:
#multi-diamensional arrays more than 2
my_lst1 = [1,2,3]
my_lst2 = [4,5,6]
my_lst3 = [7,8,9]
my_lst4 = [11,12,13]
my_lst5 = [14,15,16]
my_lst6 = [17,18,19]
my_lst7 = [21,22,23]
my_lst8 = [24,25,26]
my_lst9 = [27,28,29]
my_final_lst1 = [my_lst1,my_lst2,my_lst3]
my_final_lst2 = [my_lst4,my_lst5,my_lst6]
my_final_lst3 = [my_lst7,my_lst8,my_lst9]
my_final_lst = [my_final_lst1,my_final_lst2,my_final_lst3]
print(my_final_lst)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 12, 13], [14, 15, 16], [17, 18, 19]], [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]


In [44]:
import numpy as np

In [45]:
arr = np.array(my_final_lst)

In [46]:
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [47]:
b.dtype

dtype('float64')

In [48]:
c = np.array([[1,2,3],[4,5,6]], dtype = int)
print(c)

[[1 2 3]
 [4 5 6]]


In [49]:
c.dtype

dtype('int32')

In [50]:
c.itemsize

4

In [58]:
print(a)
print(b)
print(a.ndim)
print(b.ndim)

[1 2 3 4]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
1
2


In [59]:
print(a.itemsize)
print(b.itemsize)
print(a.size)

4
8
4


In [60]:
print(a.size)
print(b.size)

4
6


In [65]:
b.byteswap(True)

array([[3.03865e-319, 3.16202e-322],
       [1.04347e-320, 2.05531e-320],
       [2.56124e-320, 3.06716e-320]])

In [70]:
#nbytes (Total number of bytes) = itemsize * size
a.nbytes

16

In [71]:
b.size

6

In [72]:
c.nbytes

24