In [1]:
import numpy as np

In [8]:
arr = np.array([[[1,2,3]]])

In [9]:
print(arr)
print(arr.ndim)

[[[1 2 3]]]
3


In [27]:
arr1 = np.repeat(arr,6,-2)

In [28]:
print(arr1)
print(arr1.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [30]:
np.repeat([1,2],[3,4])

array([1, 1, 1, 2, 2, 2, 2])

In [33]:
arr = np.array([[1,2],[3,4]])

In [35]:
print(arr)

print(arr.ndim)

[[1 2]
 [3 4]]
2


In [41]:
np.repeat(arr,2,0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [46]:
np.repeat(arr,10,1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [47]:
arr1

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [49]:
arr2 = np.ones((5,5), dtype = int)

In [50]:
arr2 = np.ones((5,5), dtype = int)

In [52]:
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.itemsize)
print(arr2.byteswap)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2
(5, 5)
25
4
<built-in method byteswap of numpy.ndarray object at 0x000001D9EF87D8D0>


In [54]:
arr2[2,2] = 9

In [55]:
print(arr2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [57]:
arr2 = np.ones((5,5), dtype = int)
print(arr2)
arr2[1:4,1:4] = 0
print(arr2)
arr2[2,2] = 9
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [60]:
arr3 = np.ones((5,5), dtype = int)
print(arr3)

arr4 = np.zeros((3,3), dtype = int)
arr4[1,1] = 9
print(arr4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [69]:
arr3[1:4,1:4] = arr4
print(arr3)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [82]:
arr5 = np.array([1,2,3,4,5,6,7,8,9])
arr6 = arr5.reshape((3,3))
arr7 = np.full((3,4), 7)
print(arr5)
print(arr6)
print(arr7)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [87]:
np.matmul(arr6,arr7)

array([[ 42,  42,  42,  42],
       [105, 105, 105, 105],
       [168, 168, 168, 168]])

In [91]:
arr8 = np.mat(arr6, dtype = np.int32)

In [92]:
print(arr8)
print(arr8.ndim)
print(arr8.shape)
print(arr8.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


In [93]:
arr8 - 2

matrix([[-1,  0,  1],
        [ 2,  3,  4],
        [ 5,  6,  7]])

In [96]:
arr8(arr8[1:,1:]) - 3

TypeError: 'matrix' object is not callable

In [95]:
print(arr8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
print(arr8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
arr8

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [100]:
print(arr7)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [101]:
arr7-2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [102]:
arr7+2

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [103]:
arr7*2

array([[14, 14, 14, 14],
       [14, 14, 14, 14],
       [14, 14, 14, 14]])

In [104]:
arr7/2

array([[3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5]])

In [107]:
arr7%2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [108]:
arr7^2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)

In [110]:
arr7*2

array([[14, 14, 14, 14],
       [14, 14, 14, 14],
       [14, 14, 14, 14]])

In [111]:
arr7**2

array([[49, 49, 49, 49],
       [49, 49, 49, 49],
       [49, 49, 49, 49]], dtype=int32)

In [113]:
arr7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [114]:
arr7.mean(0)

array([7., 7., 7., 7.])

In [115]:
arr8

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [118]:
arr7[:,1:] = arr8

In [119]:
arr7

array([[7, 1, 2, 3],
       [7, 4, 5, 6],
       [7, 7, 8, 9]])

In [123]:
arr7.mean(1)

array([3.25, 5.5 , 7.75])

In [124]:
arr7.max(0)

array([7, 7, 8, 9])

In [125]:
arr7.max()

9

In [126]:
arr7.min()

1

In [128]:
arr7.argmax()

11

In [129]:
arr7.argmax(0)

array([0, 2, 2, 2], dtype=int64)

In [134]:
arr7.argpartition(1)

array([[1, 2, 0, 3],
       [1, 2, 0, 3],
       [0, 1, 2, 3]], dtype=int64)

In [137]:
arr7.choose(0,0)

ValueError: invalid entry in choice array

In [138]:
np.linalg.det(arr7)

LinAlgError: Last 2 dimensions of the array must be square

In [139]:
a

array([[7, 1, 2, 3],
       [7, 4, 5, 6],
       [7, 7, 8, 9]])

In [148]:
arr10 = np.vstack((1,2,5,34,3,6,8,34,1008,7,4,224,3557,32,2,7,94,22,4,44,6,89,2,1,5,7,4,0))

In [141]:
print(arr7)

[[7 1 2 3]
 [7 4 5 6]
 [7 7 8 9]]


In [150]:
print(arr10)
print(arr10.shape)
print(arr10.reshape(2,2,7))

[[   1]
 [   2]
 [   5]
 [  34]
 [   3]
 [   6]
 [   8]
 [  34]
 [1008]
 [   7]
 [   4]
 [ 224]
 [3557]
 [  32]
 [   2]
 [   7]
 [  94]
 [  22]
 [   4]
 [  44]
 [   6]
 [  89]
 [   2]
 [   1]
 [   5]
 [   7]
 [   4]
 [   0]]
(28, 1)
[[[   1    2    5   34    3    6    8]
  [  34 1008    7    4  224 3557   32]]

 [[   2    7   94   22    4   44    6]
  [  89    2    1    5    7    4    0]]]


In [194]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([6,7,8,9,10])

v1 = np.column_stack((ar1,ar2,ar1,ar2,ar1,ar1))
print(v1)
print(v1.ndim)
print(v1.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 5

In [198]:
v1 = np.vsplit(ar1, 2)
print(v1)

ValueError: vsplit only works on arrays of 2 or more dimensions

Load CSV files

In [199]:
np.getbufsize()

8192

In [204]:
np.genfromtxt("Import_data_file", dtype= np.int32, delimiter = ",")

OSError: Import_data_file not found.