In [3]:
import numpy as np
import array as arr

In [4]:
A = [1,2,3,4,5]
print(type(A))

<class 'list'>


In [5]:
a = np.array(A)

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
a.shape

(5,)

In [9]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,8,10,12,14]
my_lst3 = [7,9,11,13,15]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14],
       [ 7,  9, 11, 13, 15]])

In [11]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14],
       [ 7,  9, 11, 13, 15]])

In [13]:
a = int(input("Enter the value of a = "))
b = int(input("Enter the value of b = "))
def multiply(a, b):
    """a and b must be integer.
    input: enter the value of a and b.
    return: a*b."""
    return a * b
print(a*b)

Enter the value of a = 2
Enter the value of b = 3
6


In [51]:
a = [1,2,3,4,5,6,7,8]
print(a)
a.insert(2,2)
print(a)
a.remove(2)
print(a)
a.pop(7)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7]
