In [3]:
import numpy as np

In [4]:
arr = np.arange(1,100,2.5)

In [5]:
print(arr)

[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5 21.  23.5 26.  28.5 31.  33.5
 36.  38.5 41.  43.5 46.  48.5 51.  53.5 56.  58.5 61.  63.5 66.  68.5
 71.  73.5 76.  78.5 81.  83.5 86.  88.5 91.  93.5 96.  98.5]


In [6]:
arr.size

40

In [7]:
arr1 = arr.reshape(2,2,2,5)

In [8]:
print(arr1)

[[[[ 1.   3.5  6.   8.5 11. ]
   [13.5 16.  18.5 21.  23.5]]

  [[26.  28.5 31.  33.5 36. ]
   [38.5 41.  43.5 46.  48.5]]]


 [[[51.  53.5 56.  58.5 61. ]
   [63.5 66.  68.5 71.  73.5]]

  [[76.  78.5 81.  83.5 86. ]
   [88.5 91.  93.5 96.  98.5]]]]


In [9]:
print(arr1.ndim)

4


In [10]:
arr1[0,1,1,2]

43.5

In [11]:
arr1[:,1:,:,2:4]

array([[[[31. , 33.5],
         [43.5, 46. ]]],


       [[[81. , 83.5],
         [93.5, 96. ]]]])

In [12]:
arr1[:,:,:,0:4:2]

array([[[[ 1. ,  6. ],
         [13.5, 18.5]],

        [[26. , 31. ],
         [38.5, 43.5]]],


       [[[51. , 56. ],
         [63.5, 68.5]],

        [[76. , 81. ],
         [88.5, 93.5]]]])

In [13]:
np.zeros((2,3), dtype = np.int32)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
a = np.full((2,3),8,dtype = np.float32)

In [15]:
print(a)

[[8. 8. 8.]
 [8. 8. 8.]]


In [16]:
a[:,1:] = 4

In [17]:
a

array([[8., 4., 4.],
       [8., 4., 4.]], dtype=float32)

In [18]:
b = np.random.randint(0, 100,(3,4,5,6), dtype = np.int64)

In [19]:
b

array([[[[25, 73,  3, 38, 21, 98],
         [ 5, 74,  9, 79, 55, 58],
         [60, 75, 13, 43, 20, 99],
         [55, 15, 47, 94,  3, 70],
         [28, 26, 37,  4, 37, 36]],

        [[50,  1, 29, 68,  2, 50],
         [81, 71, 91, 10, 57, 33],
         [87, 89, 65, 75, 18, 29],
         [16, 38, 37,  3, 76, 47],
         [70, 94, 19, 54, 14, 40]],

        [[36, 77, 85, 61, 69, 13],
         [49,  7, 54, 42, 76, 50],
         [70, 96, 41, 30, 11, 99],
         [21, 10,  3,  3, 86, 87],
         [85, 17, 22, 36, 84, 86]],

        [[17, 20, 72, 86, 65, 90],
         [32, 97, 71, 87,  7, 87],
         [13, 64, 42,  7, 44, 71],
         [46, 64, 71, 28, 40, 22],
         [65, 91, 55, 46, 74, 28]]],


       [[[44, 36, 45, 77, 32, 37],
         [43, 83, 85, 65,  5, 66],
         [69, 44, 33,  9, 73, 51],
         [47, 87, 91, 68, 93, 98],
         [ 9, 70, 93, 44, 76, 78]],

        [[54, 17, 90, 37,  1, 48],
         [72,  9, 61, 91, 38, 58],
         [49, 17, 68, 68, 22, 30],
        

In [20]:
b.size

360

In [22]:
b.itemsize

8

In [32]:
c = np.identity(4, dtype = int)

In [30]:
b

array([[[[25, 73,  3, 38, 21, 98],
         [ 5, 74,  9, 79, 55, 58],
         [60, 75, 13, 43, 20, 99],
         [55, 15, 47, 94,  3, 70],
         [28, 26, 37,  4, 37, 36]],

        [[50,  1, 29, 68,  2, 50],
         [81, 71, 91, 10, 57, 33],
         [87, 89, 65, 75, 18, 29],
         [16, 38, 37,  3, 76, 47],
         [70, 94, 19, 54, 14, 40]],

        [[36, 77, 85, 61, 69, 13],
         [49,  7, 54, 42, 76, 50],
         [70, 96, 41, 30, 11, 99],
         [21, 10,  3,  3, 86, 87],
         [85, 17, 22, 36, 84, 86]],

        [[17, 20, 72, 86, 65, 90],
         [32, 97, 71, 87,  7, 87],
         [13, 64, 42,  7, 44, 71],
         [46, 64, 71, 28, 40, 22],
         [65, 91, 55, 46, 74, 28]]],


       [[[44, 36, 45, 77, 32, 37],
         [43, 83, 85, 65,  5, 66],
         [69, 44, 33,  9, 73, 51],
         [47, 87, 91, 68, 93, 98],
         [ 9, 70, 93, 44, 76, 78]],

        [[54, 17, 90, 37,  1, 48],
         [72,  9, 61, 91, 38, 58],
         [49, 17, 68, 68, 22, 30],
        

In [36]:
d = np.identity(2)

In [37]:
d

array([[1., 0.],
       [0., 1.]])

In [39]:
arr2 = np.array([1,2,3])

In [40]:
arr2

array([1, 2, 3])

In [41]:
arr2.shape

(3,)

print(a

In [42]:
print(arr2.size)
print(arr2.shape)
print(arr2.itemsize)
print(arr2.ndim)

3
(3,)
4
1


In [43]:
arr3 = np.array([[1,2,3]])

In [44]:
print(arr3)
print(arr3.ndim)

[[1 2 3]]
2


In [45]:
arr1

array([[[[ 1. ,  3.5,  6. ,  8.5, 11. ],
         [13.5, 16. , 18.5, 21. , 23.5]],

        [[26. , 28.5, 31. , 33.5, 36. ],
         [38.5, 41. , 43.5, 46. , 48.5]]],


       [[[51. , 53.5, 56. , 58.5, 61. ],
         [63.5, 66. , 68.5, 71. , 73.5]],

        [[76. , 78.5, 81. , 83.5, 86. ],
         [88.5, 91. , 93.5, 96. , 98.5]]]])

In [49]:
arr4 = np.array([[1,2,3],[4,5,6]])

In [50]:
arr4.ndim

2

In [51]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])